name: "MT Trigger main repo build"
on:
  workflow_dispatch: # manual
  push:
    branches:
      - mmathieum

jobs:
  MT-TRIGGER-MAIN-REPO-BUILD:
    name: "MT Trigger main repo build"
    runs-on: ubuntu-latest
    steps:
      - name: "MT Trigger main repo build"
        run: gh workflow run mt-sync-code-data.yml --ref mmathieum --repo mtransitapps/mtransit-for-android
        env:
          GH_TOKEN: ${{ secrets.MT_PAT }}
