name: "MT Trigger main repo build"
on:
  workflow_dispatch: # manual
  push:
    branches:
      - master
      - mmathieum

jobs:
  MT-TRIGGER-MAIN-REPO-BUILD:
    name: "MT Trigger main repo build"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: MT setup MT_GIT_BRANCH env
        run: |
          echo "MT_GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: "MT Trigger main repo build"
        run: gh workflow run mt-sync-code-data.yml --ref $MT_GIT_BRANCH --repo mtransitapps/mtransit-for-android
        env:
          GH_TOKEN: ${{ secrets.MT_PAT }}
