name: "MT Trigger main repo build"
on:
  workflow_dispatch: # manual
  push:
    branches:
      - master
      - mmathieum # TO BE DELETED

jobs:
  MT-TRIGGER-MAIN-REPO-BUILD:
    name: "MT Trigger main repo build"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: MT setup MT_GIT_BRANCH env
        run: |
          echo "MT_GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: "MT Trigger main repo build"
        id: trigger-mt-sync-code
        continue-on-error: true
        run: gh workflow run mt-sync-code.yml --ref $MT_GIT_BRANCH --repo mtransitapps/mtransit-for-android
        env:
          GH_TOKEN: ${{ secrets.MT_PAT }}
      - name: "MT Trigger main repo build (backward compat)"
        if: steps.trigger-mt-sync-code.outcome == 'failure'
        run: gh workflow run mt-sync-code-data.yml --ref $MT_GIT_BRANCH --repo mtransitapps/mtransit-for-android
        env:
          GH_TOKEN: ${{ secrets.MT_PAT }}
